version: '3'
services:
  postgres:
    image: postgres:14.4-alpine
    hostname: postgres
    ports:
      - '6000:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
volumes:
  postgres:
